### ISSUE TITLE
User Manager Details should include whether or not user has admin/operator access

### ISSUE THREAD

**Issue by dlavigne** [trueos/sysadm-ui-qt#6]
When you create a new user, you have the option to grant administrator and/or operator access. However, once the user is created, the Details view doesn't indicate which users have what access.

**Comment by beanpole135** [comment]
This is intentional.
The new "groups" tab (which was just enabled a few minutes ago) allows easy view/modification of the user permission levels via which groups the user is in.

I also added status tips to the new user permission checkboxes to give more info about which group corresponds to which checkbox.

https://github.com/trueos/sysadm-ui-qt/commit/d1edf85aae8efb036d885fbf98169a6b13a33e0b
